//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP.NetMVCExample.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyWorkers
    {
        public int CompanyID { get; set; }
        public int UserID { get; set; }
        public int RoleID { get; set; }
        public int OfficeID { get; set; }
        public int WorkerID { get; set; }
    
        public virtual CompanyRoles CompanyRoles { get; set; }
        public virtual Companys Companys { get; set; }
        public virtual Offices Offices { get; set; }
        public virtual Users Users { get; set; }
    }
}
