//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP.NetMVCExample.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanysCompanyAddressBooks
    {
        public int OwersID { get; set; }
        public int UsersID { get; set; }
        public bool Affiliated { get; set; }
        public bool Verified { get; set; }
    
        public virtual Companys Companys { get; set; }
        public virtual Users Users { get; set; }
    }
}
