//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace ASP.NetMVCExample.Models
{
    public partial class CompanyWorker
    {
        public int CompanyID { get; set; }
        public int UserID { get; set; }
        public int RoleID { get; set; }
        public int WorkerID { get; set; }
        public int OfficeID { get; set; }

        public virtual CompanyRole CompanyRole { get; set; }
        public virtual Company Company { get; set; }
        public virtual User User { get; set; }
        public virtual Office Office { get; set; }
    }
}
