//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace ASP.NetMVCExample.Models
{
    using System;
    using System.Collections.Generic;

    public partial class CompanyRole
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CompanyRole()
        {
            this.CompanyWorkers = new HashSet<CompanyWorker>();
            this.CompanyRoles1 = new HashSet<CompanyRole>();
        }

        public int RoleID { get; set; }
        public int CompanyID { get; set; }
        public string RoleName { get; set; }
        public Nullable<int> SuperRole { get; set; }
        public bool Admin { get; set; }

        public virtual Company Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanyWorker> CompanyWorkers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanyRole> CompanyRoles1 { get; set; }
        public virtual CompanyRole CompanyRole1 { get; set; }
    }
}
