//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP.NetMVCExample.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectFiles
    {
        public int FileID { get; set; }
        public int ProjectID { get; set; }
        public byte[] File { get; set; }
    
        public virtual Projects Projects { get; set; }
    }
}
