//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace ASP.NetMVCExample.Models
{
    public partial class ProjectFile
    {
        public int FileID { get; set; }
        public int ProjectID { get; set; }
        public byte[] File { get; set; }

        public virtual Project Project { get; set; }
    }
}
