//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP.NetMVCExample.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectTaskTypeManagers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProjectTaskTypeManagers()
        {
            this.Projects = new HashSet<Projects>();
        }
    
        public int ProjectTaskTypeManagersID { get; set; }
        public int TaskTypeID { get; set; }
        public Nullable<int> ManagerID { get; set; }
        public Nullable<int> ManagingCompanysID { get; set; }
    
        public virtual Companys Companys { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Projects> Projects { get; set; }
        public virtual Users Users { get; set; }
    }
}
